openapi: 3.0.0
info:
  title: API Thử Thách
  version: 1.0.0
  description: API để lấy thông tin các thử thách bài đăng, có thể lọc theo ID người dùng
servers:
  - url: http://localhost:5000
    description: Máy chủ cục bộ
paths:
  /api/challenges:
    get:
      summary: Lấy danh sách các thử thách bài đăng
      description: Lấy danh sách tất cả thử thách bài đăng
      tags:
        - Challenges
      parameters:
        - in: query
          name: userId
          required: false
          schema:
            type: integer
          description: ID của người dùng để theo dõi hành động (không ảnh hưởng đến kết quả truy vấn)
      responses:
        "200":
          description: Thành công - Danh sách các thử thách bài đăng
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message: 
                    type: string
                    example: "Post challenges retrieved successfully"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/PostChallenge"
        "500":
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  /api/challenges/{id}:
    get:
      summary: Lấy chi tiết thử thách bài đăng theo ID
      description: Lấy thông tin chi tiết của một thử thách bài đăng dựa trên ID
      tags:
        - Challenges
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID của thử thách bài đăng
        - in: query
          name: userId
          required: false
          schema:
            type: integer
          description: ID của người dùng để theo dõi hành động (không ảnh hưởng đến kết quả truy vấn)
      responses:
        "200":
          description: Thành công - Chi tiết thử thách bài đăng
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Post challenge retrieved successfully"
                  data:
                    $ref: "#/components/schemas/PostChallenge"
        "404":
          description: Không tìm thấy thử thách bài đăng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "Failed to retrieve post challenges"
        error:
          type: string
          example: "Internal Server Error"
    PostChallenge:
      type: object
      properties:
        id:
          type: integer
          example: 1
        type:
          type: string
          enum: ["comment", "event"]
          example: "comment"
        promo_id:
          type: integer
          example: 101
          nullable: true
        challenge_id:
          type: integer
          example: 201
          nullable: true
        post_id:
          type: integer
          example: 301
          nullable: true
        event_id:
          type: integer
          example: 401
          nullable: true
        is_show:
          type: boolean
          example: false
        points_reward:
          type: integer
          example: 100
        due_date:
          type: string
          format: date-time
          example: "2025-06-01T00:00:00Z"
          nullable: true
        created_at:
          type: string
          format: date-time
          example: "2025-05-18T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-05-18T00:00:00Z"
