openapi: 3.0.0
info:
  title: Challenge API
  version: 1.0.0
  description: API để lấy thông tin các challenge, có thể lọc theo community_member_id
servers:
  - url: http://localhost:5000
    description: Local server
paths:
  /api/challenges:
    get:
      summary: Lấy danh sách challenge theo community_member_id
      parameters:
        - in: query
          name: userId
          required: false
          schema:
            type: integer
          description: ID của thành viên cộng đồng để lọc challenge
      responses:
        '200':
          description: Danh sách challenge
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Challenge'
  /api/challenges/{id}:
    get:
      summary: Lấy chi tiết challenge theo ID và community_member_id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID của challenge
        - in: query
          name: userId
          required: false
          schema:
            type: integer
          description: ID của thành viên cộng đồng (để kiểm tra quyền truy cập hoặc lọc)
      responses:
        '200':
          description: Chi tiết challenge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenge'
        '404':
          description: Không tìm thấy challenge
components:
  schemas:
    Challenge:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Challenge đầu tiên"
        description:
          type: string
          example: "Chi tiết về challenge"
        reward_type:
          type: string
          enum: ["points", "voucher", "badge", "other"]
          example: "points"
        reward_value:
          type: string
          example: "100"
        due_date:
          type: string
          format: date-time
          example: "2025-06-01T00:00:00Z"
        status:
          type: string
          enum: ["pending", "done"]
          example: "pending"
        is_weekly:
          type: boolean
          example: false
        recurrence_rule:
          type: object
          example: {}
        community_member_id:
          type: integer
          example: 1
        comments_count:
          type: integer
          example: 0
        created_at:
          type: string
          format: date-time
          example: "2025-05-18T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-05-18T00:00:00Z"